import { Metadata } from "next";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: `Read the disclaimer for ${siteConfig.name}. Understand the limitations of our free online tools and calculators.`,
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <h1 className="text-4xl font-bold tracking-tight text-foreground">
        Disclaimer
      </h1>
      <p className="mt-4 text-sm text-muted-foreground">
        Last updated: March 27, 2026
      </p>

      <div className="mt-8 space-y-8 text-muted-foreground leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold text-foreground">
            General Information
          </h2>
          <p className="mt-3">
            The information and tools provided on {siteConfig.name} are for
            general informational and educational purposes only. They are not
            intended to serve as professional financial, medical, legal, or any
            other type of advice.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">
            No Professional Advice
          </h2>
          <p className="mt-3">
            The results generated by our calculators and tools should not be
            considered a substitute for professional consultation. Always seek
            the advice of a qualified professional for matters related to
            finance, health, law, or any other specialized field.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">
            Accuracy of Information
          </h2>
          <p className="mt-3">
            While we make every effort to ensure that the information and
            calculations provided are accurate and up-to-date, {siteConfig.name}{" "}
            makes no warranties or representations of any kind, express or
            implied, about the completeness, accuracy, reliability, or
            suitability of the information.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">
            Use at Your Own Risk
          </h2>
          <p className="mt-3">
            Any reliance you place on the information or results from our tools
            is strictly at your own risk. {siteConfig.name} shall not be held
            responsible for any loss or damage, including without limitation,
            indirect or consequential loss or damage, arising from the use of
            our website.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">
            External Links
          </h2>
          <p className="mt-3">
            Our website may include links to external websites for your
            convenience. We have no control over the content of those sites and
            accept no responsibility for them or for any loss or damage that may
            arise from your use of them.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">
            Contact Us
          </h2>
          <p className="mt-3">
            If you have any questions about this Disclaimer, please contact us at{" "}
            <a
              href="mailto:contact@softzar.com"
              className="text-primary hover:underline"
            >
              contact@softzar.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
